CREATE TABLE Story (
	id INTEGER,
	title CHAR(64),
	feature CHAR(64),
	issue_id INTEGER NOT NULL,
	script TEXT,
	pencils CHAR(64),
	inks CHAR(64),
	colors CHAR(64),
	letters CHAR(64),
	editing TEXT,
	genre CHAR(64),
	characters TEXT,
	synopsis TEXT,
	reprint_notes TEXT,
	notes TEXT,
	type_id INTEGER NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (issue_id) REFERENCES Issue(id),
	FOREIGN KEY (type_id) REFERENCES Story_Type(id)
)

CREATE TABLE Series (
	id INTEGER,
	name CHAR(64),
	format TEXT,
	year_began INTEGER,
	year_ended INTEGER,
	publication_dates CHAR(20),
	first_issue_id INTEGER,
	last_issue_id INTEGER,
	publisher_id INTEGER,
	country_id INTEGER,
	language_id INTEGER,
	notes TEXT,
	color TEXT,
	dimensions CHAR(20),
	paper_stock TEXT,
	binding TEXT,
	publishing_format TEXT,
	publication_type_id INTEGER,
	PRIMARY KEY (id),
	FOREIGN KEY (first_issue_id) REFERENCES Issue(id),
	FOREIGN KEY (last_issue_id) REFERENCES Issue(id),
	FOREIGN KEY (publisher_id) REFERENCES Publisher(id),
	FOREIGN KEY (language_id) REFERENCES Language(id)
)